# -*- coding: utf-8 -*-
"""Notebook_de_prueba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zWPla5ZmiogVw20whvIR3l-pzpZW7cie
"""

### GENERADOR ALEATORIO DE ORACIONES ###
import random

# random.choice([])

NUMERO = random.choice(['SINGULAR', 'PLURAL'])
GENERO = random.choice(['MASCULINO', 'FEMENINO'])
if GENERO == 'MASCULINO':
  gen1 = 'o'
  gen2 = ''
if GENERO == 'FEMENINO':
  gen1 = 'a'
  gen2 = 'a'

FN3_sust_NO = ''
if NUMERO == 'SINGULAR':
  if GENERO == 'MASCULINO':
    FN3_sust = random.choice(['caballo ', 'perro ', 'presidente ', 'portón ', 'sol '])
  if GENERO == 'FEMENINO':
    FN3_sust = random.choice(['vaca ', 'gata ', 'ministra ', 'puerta ', 'luna '])
if NUMERO == 'PLURAL':
  if GENERO == 'MASCULINO':
    FN3_sust = random.choice(['caballos ', 'perros ', 'presidentes ', 'portones ', 'soles '])
  if GENERO == 'FEMENINO':
    FN3_sust = random.choice(['vacas ', 'gatas ', 'ministras ', 'puertas ', 'lunas '])
FN3 = random.choice([FN3_sust, FN3_sust_NO])
FN2_preadj_NO = ''
FN2_preadj_calif_P = random.choice(['bonit@s ', 'fe@s ', 'grandes ', 'pequeñ@s ', 'abominables ', 'amables ', 'terribles '])
FN2_preadj_calif_S = random.choice(['bonit@ ', 'fe@ ', 'gran ', 'pequeñ@ ', 'abominable ', 'amable ', 'terrible '])
if NUMERO == 'SINGULAR':
  FN2_preadj_calif = FN2_preadj_calif_S
if NUMERO == 'PLURAL':
  FN2_preadj_calif = FN2_preadj_calif_P
FN2 = random.choice([FN2_preadj_NO, FN2_preadj_calif])
FN1_NO = ''
FN1_preadj_NO = ''
FN1_preadj_num_P = random.choice(['dos ', 'tres ', 'cuatro ', 'much@s ', 'poc@s ', 'demasiad@s '])
FN1_preadj_num_S = random.choice(['much@ ', 'poc@ ', 'demasiad@ '])
if NUMERO == 'SINGULAR':
  FN1_preadj_num = FN1_preadj_num_S
if NUMERO == 'PLURAL':
  FN1_preadj_num = FN1_preadj_num_P
FN1 = random.choice([FN1_preadj_num, FN1_preadj_NO])
FN_pre_NO = ''
FN_pos_P1 = 'mis '
FN_pos_P2 = 'tus '
FN_pos_P3 = 'sus '
FN_pos_P1P = 'nuestr@s '
FN_pos_P = random.choice([FN_pos_P1, FN_pos_P2, FN_pos_P3, FN_pos_P1P])
FN_pos_S1 = 'mi '
FN_pos_S2 = 'tu '
FN_pos_S3 = 'su '
FN_pos_S1P = 'nuestr@ '
FN_pos_S = random.choice([FN_pos_S1, FN_pos_S2, FN_pos_S3, FN_pos_S1P])
FN_pos = random.choice([FN_pos_S, FN_pos_P])
FN_art_PFN = 'unas '
FN_art_PFD = 'las '
FN_art_PF = random.choice([FN_art_PFD, FN_art_PFN])
FN_art_PMN = 'unos '
FN_art_PMD = 'los '
FN_art_PM = random.choice([FN_art_PMD, FN_art_PMN])
FN_art_SFN = 'una '
FN_art_SFD = 'la '
FN_art_SF = random.choice([FN_art_SFD, FN_art_SFN])
FN_art_SMN = 'un '
FN_art_SMD = 'el '
FN_art_SM = random.choice([FN_art_SMD, FN_art_SMN])
if GENERO == 'MASCULINO':
  FN_art_S = FN_art_SM
  FN_art_P = FN_art_PM
if GENERO == 'FEMENINO':
  FN_art_S = FN_art_SF
  FN_art_P = FN_art_PF
if NUMERO == 'SINGULAR':
  FN_art = FN_art_S
  FN_pos = FN_pos_S
if NUMERO == 'PLURAL':
  FN_art = FN_art_P
  FN_pos = FN_pos_P
FN_pre = random.choice([FN_art, FN_pos])
if FN2 == FN2_preadj_calif:
  FN_pre_NO = FN_pre
if FN1_preadj_num in ['demasiad@s ', 'demasiad@ ', 'much@s ', 'much@ ']:
  FN_pre = ''
pre = random.choice([FN_pre, FN_pre_NO])
O = pre + FN1 + FN2 + FN3
O_gen1 = O.replace('@', gen1)
O_gen2 = O_gen1.replace('$', gen2)
print(O_gen2)

### CONSTRUCTOR DE FRASES NOMINALES ###
import random

#random.choice([])

GEN = ''
NUM = ''
C = ''
ART = ''
CUANTI = ''
CUANTInosus = ''
CUANTIsus = ''
CUANTIyes = ''
FN = ''
POS = ''
POSADJ = ''
POSADJyes = ''
POSyes = ''
PREADJ = ''
PREADJyes = ''
PREFIX = ''

# GÉNERO Y NÚMERO

GEN = random.choice(["MASCULINO", "FEMENINO"])
NUM = random.choice(["SINGULAR", "PLURAL"])

# CABEZA

if GEN == "MASCULINO" and NUM == "SINGULAR":
  C = random.choice(['perro ', 'gato ', 'hombre ', 'presidente ', 'ministro ', 'bombero ', 'capitán ', 'herrero ', 'profesor ', 'programador ', 'hermano ', 'sacerdote '])
if GEN == "MASCULINO" and NUM == "PLURAL":
  C = random.choice(['perros ', 'gatos ', 'hombres ', 'presidentes ', 'ministros ', 'bomberos ', 'capitanes ', 'herreros ', 'profesores ', 'programadores ', 'hermanos ', 'sacerdotes '])
if GEN == "FEMENINO" and NUM == "SINGULAR":
  C = random.choice(['leona ', 'gata ', 'mujer ', 'ministra ', 'lideresa ', 'enfermera ', 'capitana ', 'bibliotecaria ', 'profesora ', 'programadora ', 'hermana ', 'sacerdotiza '])
if GEN == "FEMENINO" and NUM == "PLURAL":
  C = random.choice(['leonas ', 'gatas ', 'mujeres ', 'ministras ', 'lideresas ', 'enfermeras ', 'capitanas ', 'bibliotecarias ', 'profesoras ', 'programadoras ', 'hermanas ', 'sacerdotizas '])

# CON POSADJ O SIN POSADJ

if NUM == "SINGULAR":
  POSADJyes = random.choice(['roj@ ', 'solter@ ', 'valiente ', 'soberbi@ ', 'peruan@ ', 'campestre ', 'frances$ '])
if NUM == "PLURAL":
  POSADJyes = random.choice(['roj@s ', 'solter@s ', 'valientes ', 'soberbi@s ', 'peruan@s ', 'campestres ', 'frances&s '])
POSADJ = random.choice([POSADJyes, ''])
# POSADVyes = random.choice(['extremadamente'])
# if POSADJ == POSADJyes:
  # POSADV = random.choice([POSADVyes, ''])

# CON PREADJ O SIN PREADJ

if NUM == "SINGULAR":
  PREADJyes = random.choice(['terrible ', 'increíble ', 'gran ', 'grandios@ ', 'magnífic@ ', 'viej@ '])
if NUM == "PLURAL":
  PREADJyes = random.choice(['terribles ', 'increíbles ', 'grandes ', 'grandios@s ', 'magnífic@s ', 'viej@s '])
PREADJ = random.choice([PREADJyes, ''])

# CON CUANTI O SIN CUANTI

if PREADJ != PREADJyes:
  if NUM == "SINGULAR":
    CUANTIsus = random.choice(['tod@ ', 'cualquier ', 'cada ', 'algun$ '])
    CUANTInosus = ''
  if NUM == "PLURAL":
    CUANTIsus = random.choice(['demasiad@s ', 'vari@s ', 'algun@s '])
    CUANTInosus = random.choice(['poc@s ','dos ','tres ','cuatro ','cinco '])
  CUANTIyes = random.choice([CUANTIsus, CUANTInosus])
  CUANTI = random.choice([CUANTIyes, ''])
  if CUANTI == CUANTIsus:
    PREFIX = 'BLOQ' # Bloqueo
  else:
    PREFIX = 'ART'
elif PREADJ == PREADJyes:
  PREFIX = 'ART'

# CON POSESIVO O SIN POSESIVO

if PREFIX != 'BLOQ':
  if NUM == "SINGULAR":
    POSyes = random.choice(['mi ', 'tu ', 'su ', 'nuestr@ '])
  if NUM == "PLURAL":
    POSyes == random.choice(['mis ', 'tus ', 'sus ', 'nuestr@s '])
  POS = random.choice([POSyes, 'ART'])
  PREFIX = POS

# CON ARTICULO

if PREFIX == 'ART':
  if GEN == "MASCULINO" and NUM == "SINGULAR":
    ART = random.choice(['el ', 'un '])
  if GEN == "MASCULINO" and NUM == "PLURAL":
    ART = random.choice(['los ', 'unos '])
  if GEN == "FEMENINO" and NUM == "SINGULAR":
    ART = random.choice(['la ', 'una '])
  if GEN == "FEMENINO" and NUM == "PLURAL":
    ART = random.choice(['las ', 'unas '])

# REAFIX

if PREFIX == 'BLOQ':
  PREFIX = ''
if PREFIX == 'ART':
  PREFIX = ART

# MERGE

FN = PREFIX + CUANTI + PREADJ + C + POSADJ

# REAJUST

if GEN == "MASCULINO":
  FN = FN.replace("@", "o")
  FN = FN.replace("$", "")
  FN = FN.replace("&", "e")
if GEN == "FEMENINO":
  FN = FN.replace("@", "a")
  FN = FN.replace("$", "a")
  FN = FN.replace("&", "a")

# PRINT

# print(FN)

### ALARGADOR DE FRASES NOMINALES

COORD1 = FN + "y "
FN = random.choice([FN, COORD1])

## SEGUNDA FRASE NOMINAL

GEN = ''
NUM = ''
C = ''
ART = ''
CUANTI = ''
CUANTInosus = ''
CUANTIsus = ''
CUANTIyes = ''
POS = ''
POSADJ = ''
POSADJyes = ''
POSyes = ''
PREADJ = ''
PREADJyes = ''
PREFIX = ''

# GÉNERO Y NÚMERO

GEN = random.choice(["MASCULINO", "FEMENINO"])
NUM = random.choice(["SINGULAR", "PLURAL"])

# CABEZA

if GEN == "MASCULINO" and NUM == "SINGULAR":
  C = random.choice(['perro ', 'gato ', 'hombre ', 'presidente ', 'ministro ', 'bombero ', 'capitán ', 'herrero ', 'profesor ', 'programador ', 'hermano ', 'sacerdote '])
if GEN == "MASCULINO" and NUM == "PLURAL":
  C = random.choice(['perros ', 'gatos ', 'hombres ', 'presidentes ', 'ministros ', 'bomberos ', 'capitanes ', 'herreros ', 'profesores ', 'programadores ', 'hermanos ', 'sacerdotes '])
if GEN == "FEMENINO" and NUM == "SINGULAR":
  C = random.choice(['leona ', 'gata ', 'mujer ', 'ministra ', 'lideresa ', 'enfermera ', 'capitana ', 'bibliotecaria ', 'profesora ', 'programadora ', 'hermana ', 'sacerdotiza '])
if GEN == "FEMENINO" and NUM == "PLURAL":
  C = random.choice(['leonas ', 'gatas ', 'mujeres ', 'ministras ', 'lideresas ', 'enfermeras ', 'capitanas ', 'bibliotecarias ', 'profesoras ', 'programadoras ', 'hermanas ', 'sacerdotizas '])

# CON POSADJ O SIN POSADJ

if NUM == "SINGULAR":
  POSADJyes = random.choice(['roj@ ', 'solter@ ', 'valiente ', 'soberbi@ ', 'peruan@ ', 'campestre ', 'frances$ '])
if NUM == "PLURAL":
  POSADJyes = random.choice(['roj@s ', 'solter@s ', 'valientes ', 'soberbi@s ', 'peruan@s ', 'campestres ', 'frances&s '])
POSADJ = random.choice([POSADJyes, ''])
# POSADVyes = random.choice(['extremadamente'])
# if POSADJ == POSADJyes:
  # POSADV = random.choice([POSADVyes, ''])

# CON PREADJ O SIN PREADJ

if NUM == "SINGULAR":
  PREADJyes = random.choice(['terrible ', 'increíble ', 'gran ', 'grandios@ ', 'magnífic@ ', 'viej@ '])
if NUM == "PLURAL":
  PREADJyes = random.choice(['terribles ', 'increíbles ', 'grandes ', 'grandios@s ', 'magnífic@s ', 'viej@s '])
PREADJ = random.choice([PREADJyes, ''])

# CON CUANTI O SIN CUANTI

if PREADJ != PREADJyes:
  if NUM == "SINGULAR":
    CUANTIsus = random.choice(['tod@ ', 'cualquier ', 'cada ', 'algun$ '])
    CUANTInosus = ''
  if NUM == "PLURAL":
    CUANTIsus = random.choice(['demasiad@s ', 'vari@s ', 'algun@s '])
    CUANTInosus = random.choice(['poc@s ','dos ','tres ','cuatro ','cinco '])
  CUANTIyes = random.choice([CUANTIsus, CUANTInosus])
  CUANTI = random.choice([CUANTIyes, ''])
  if CUANTI == CUANTIsus:
    PREFIX = 'BLOQ' # Bloqueo
  else:
    PREFIX = 'ART'
elif PREADJ == PREADJyes:
  PREFIX = 'ART'

# CON POSESIVO O SIN POSESIVO

if PREFIX != 'BLOQ':
  if NUM == "SINGULAR":
    POSyes = random.choice(['mi ', 'tu ', 'su ', 'nuestr@ '])
  if NUM == "PLURAL":
    POSyes == random.choice(['mis ', 'tus ', 'sus ', 'nuestr@s '])
  POS = random.choice([POSyes, 'ART'])
  PREFIX = POS


# CON ARTICULO

if PREFIX == 'ART':
  if GEN == "MASCULINO" and NUM == "SINGULAR":
    ART = random.choice(['el ', 'un '])
  if GEN == "MASCULINO" and NUM == "PLURAL":
    ART = random.choice(['los ', 'unos '])
  if GEN == "FEMENINO" and NUM == "SINGULAR":
    ART = random.choice(['la ', 'una '])
  if GEN == "FEMENINO" and NUM == "PLURAL":
    ART = random.choice(['las ', 'unas '])

# REAFIX

if PREFIX == 'BLOQ':
  PREFIX = ''
if PREFIX == 'ART':
  PREFIX = ART

# MERGE

FN2 = PREFIX + CUANTI + PREADJ + C + POSADJ

# REAJUST

if GEN == "MASCULINO":
  FN2 = FN2.replace("@", "o")
  FN2 = FN2.replace("$", "")
  FN2 = FN2.replace("&", "e")
if GEN == "FEMENINO":
  FN2 = FN2.replace("@", "a")
  FN2 = FN2.replace("$", "a")
  FN2 = FN2.replace("&", "a")

# INSERTION

if FN == COORD1:
 FN = FN + FN2

print(FN)

### CONSTRUCTOR DE FRASES NOMINALES ###
# TERMINADO.
import random

#random.choice([])

# RESET

GEN = ''
NUM = ''
C = ''
ART = ''
CUANTI = ''
CUANTInosus = ''
CUANTIsus = ''
CUANTIyes = ''
POS = ''
POSADJ = ''
POSADJyes = ''
POSyes = ''
PREADJ = ''
PREADJyes = ''
PREFIX = ''
FN = ''

# GÉNERO Y NÚMERO

GEN = random.choice(["MASCULINO", "FEMENINO"])
NUM = random.choice(["SINGULAR", "PLURAL"])

# CABEZA

if GEN == "MASCULINO" and NUM == "SINGULAR":
  C = random.choice(['perro ', 'gato ', 'hombre ', 'presidente ', 'ministro ', 'enfermero ', 'capitán ', 'bibliotecario ', 'profesor ', 'programador ', 'hermano ', 'sacerdote ', 'alumno '])
if GEN == "MASCULINO" and NUM == "PLURAL":
  C = random.choice(['perros ', 'gatos ', 'hombres ', 'presidentes ', 'ministros ', 'enfermeros ', 'capitanes ', 'bibliotecarios ', 'profesores ', 'programadores ', 'hermanos ', 'sacerdotes ', 'alumnos '])
if GEN == "FEMENINO" and NUM == "SINGULAR":
  C = random.choice(['perra ', 'gata ', 'mujer ', 'presidenta ', 'ministra ', 'enfermera ', 'capitana ', 'bibliotecaria ', 'profesora ', 'programadora ', 'hermana ', 'sacerdotiza ', 'alumna '])
if GEN == "FEMENINO" and NUM == "PLURAL":
  C = random.choice(['perras ', 'gatas ', 'mujeres ', 'presidentas ', 'ministras ', 'enfermeras ', 'capitanas ', 'bibliotecarias ', 'profesoras ', 'programadoras ', 'hermanas ', 'sacerdotizas ', 'alumnas '])

print(GEN)
print(NUM)
print(C)

# POSADJ

if NUM == "SINGULAR":
  POSADJyes = random.choice(['roj@ ', 'solter@ ', 'valiente ', 'soberbi@ ', 'peruan@ ', 'campestre ', 'frances$ ', 'actual ', 'antigu@ ', 'expert@ ', 'corrupt@ ', 'ladron$ '])
if NUM == "PLURAL":
  POSADJyes = random.choice(['roj@s ', 'solter@s ', 'valientes ', 'soberbi@s ', 'peruan@s ', 'campestres ', 'frances&s ', 'actuales ', 'antigu@s ', 'expert@s ', 'corrupt@s ', 'ladron&s '])
POSADJ = random.choice([POSADJyes, ''])

print(POSADJyes)
print(POSADJ == POSADJyes)
print(C + POSADJ)

# PREADJ

if NUM == "SINGULAR":
  PREADJyes = random.choice(['terrible ', 'increíble ', 'gran ', 'grandios@ ', 'magnífic@ ', 'viej@ '])
if NUM == "PLURAL":
  PREADJyes = random.choice(['terribles ', 'increíbles ', 'grandes ', 'grandios@s ', 'magnífic@s ', 'viej@s '])
PREADJ = random.choice([PREADJyes, ''])

print(PREADJyes)
print(PREADJ == PREADJyes)
print(PREADJ + C + POSADJ)

# CUANTI

if NUM == "SINGULAR":
  CUANTIsus = random.choice(['tod@ ', 'cualquier ', 'cada ', 'algun$ ', 'ningun$ '])
  CUANTInosus = ''
if NUM == "PLURAL":
  CUANTIsus = random.choice(['demasiad@s ', 'vari@s ', 'algun@s '])
  CUANTInosus = random.choice(['poc@s ','dos ','tres ','cuatro ','cinco '])
CUANTIyes = random.choice([CUANTIsus, CUANTInosus])
CUANTI = random.choice([CUANTIyes, ''])

print(CUANTIyes)
print(CUANTI != '')
print(CUANTI + PREADJ + C + POSADJ)

# POS

if not CUANTI == CUANTIsus:
  if NUM == "SINGULAR":
    POSyes = random.choice(['mi ', 'tu ', 'su ', 'nuestr@ '])
  if NUM == "PLURAL":
    POSyes == random.choice(['mis ', 'tus ', 'sus ', 'nuestr@s '])
  POS = random.choice([POSyes, ''])
else:
  POS = ''

print(POSyes)
print(POS == POSyes)
print(POS + CUANTI + PREADJ + C + POSADJ)

# ART

if not CUANTI == CUANTIsus and POS == '':
  if GEN == "MASCULINO" and NUM == "SINGULAR":
    ART = random.choice(['el ', 'un '])
  if GEN == "MASCULINO" and NUM == "PLURAL":
    ART = random.choice(['los ', 'unos '])
  if GEN == "FEMENINO" and NUM == "SINGULAR":
    ART = random.choice(['la ', 'una '])
  if GEN == "FEMENINO" and NUM == "PLURAL":
    ART = random.choice(['las ', 'unas '])

print(not CUANTI == CUANTIsus)
print(POS == '')
print(ART + POS + CUANTI + PREADJ + C + POSADJ)

# REFIX

FN = ART + POS + CUANTI + PREADJ + C + POSADJ
if GEN == "MASCULINO":
  FN = FN.replace("@", "o")
  FN = FN.replace("$", "")
  FN = FN.replace("&", "e")
if GEN == "FEMENINO":
  FN = FN.replace("@", "a")
  FN = FN.replace("$", "a")
  FN = FN.replace("&", "a")
FN = FN.replace("/", "")

# PRINT

print(FN)

### CONSTRUCTOR DE FRASES NOMINALES ###
# TERMINADO. v2
import random

#random.choice([])

# RESET

GEN = ''
NUM = ''
C = ''
ART = ''
CUANTI = ''
CUANTInosus = ''
CUANTIsus = ''
CUANTIyes = ''
POS = ''
POSADJ = ''
POSADJyes = ''
POSyes = ''
PREADJ = ''
PREADJyes = ''
PREFIX = ''
FN = ''

# GÉNERO Y NÚMERO

GEN = random.choice(["MASCULINO", "FEMENINO"])
NUM = random.choice(["SINGULAR", "PLURAL"])

# CABEZA

if GEN == "MASCULINO" and NUM == "SINGULAR":
  C = random.choice(['perro ', 'gato ', 'hombre ', 'presidente ', 'ministro ', 'enfermero ', 'capitán ', 'bibliotecario ', 'profesor ', 'programador ', 'hermano ', 'sacerdote ', 'alumno '])
if GEN == "MASCULINO" and NUM == "PLURAL":
  C = random.choice(['perros ', 'gatos ', 'hombres ', 'presidentes ', 'ministros ', 'enfermeros ', 'capitanes ', 'bibliotecarios ', 'profesores ', 'programadores ', 'hermanos ', 'sacerdotes ', 'alumnos '])
if GEN == "FEMENINO" and NUM == "SINGULAR":
  C = random.choice(['perra ', 'gata ', 'mujer ', 'presidenta ', 'ministra ', 'enfermera ', 'capitana ', 'bibliotecaria ', 'profesora ', 'programadora ', 'hermana ', 'sacerdotiza ', 'alumna '])
if GEN == "FEMENINO" and NUM == "PLURAL":
  C = random.choice(['perras ', 'gatas ', 'mujeres ', 'presidentas ', 'ministras ', 'enfermeras ', 'capitanas ', 'bibliotecarias ', 'profesoras ', 'programadoras ', 'hermanas ', 'sacerdotizas ', 'alumnas '])

# print(GEN)
# print(NUM)
# print(C)

# POSADJ

if NUM == "SINGULAR":
  POSADJyes = random.choice(['roj@ ', 'solter@ ', 'valiente ', 'soberbi@ ', 'peruan@ ', 'campestre ', 'frances$ ', 'actual ', 'antigu@ ', 'expert@ ', 'corrupt@ ', 'ladron$ '])
if NUM == "PLURAL":
  POSADJyes = random.choice(['roj@s ', 'solter@s ', 'valientes ', 'soberbi@s ', 'peruan@s ', 'campestres ', 'frances&s ', 'actuales ', 'antigu@s ', 'expert@s ', 'corrupt@s ', 'ladron&s '])
POSADJ = random.choice([POSADJyes, ''])

# print(POSADJyes)
# print(POSADJ == POSADJyes)
# print(C + POSADJ)

# PREADJ

if NUM == "SINGULAR":
  PREADJyes = random.choice(['terrible ', 'increíble ', 'gran ', 'grandios@ ', 'magnífic@ ', 'viej@ '])
if NUM == "PLURAL":
  PREADJyes = random.choice(['terribles ', 'increíbles ', 'grandes ', 'grandios@s ', 'magnífic@s ', 'viej@s '])
PREADJ = random.choice([PREADJyes, ''])

# print(PREADJyes)
# print(PREADJ == PREADJyes)
# print(PREADJ + C + POSADJ)

# CUANTI

if NUM == "SINGULAR":
  CUANTIsus = random.choice(['tod@ ', 'cualquier ', 'cada ', 'algun$ ', 'ningun$ '])
  CUANTInosus = ''
if NUM == "PLURAL":
  CUANTIsus = random.choice(['demasiad@s ', 'vari@s ', 'algun@s '])
  CUANTInosus = random.choice(['poc@s ','dos ','tres ','cuatro ','cinco '])
CUANTIyes = random.choice([CUANTIsus, CUANTInosus])
CUANTI = random.choice([CUANTIyes, ''])

# print(CUANTIyes)
# print(CUANTI != '')
# print(CUANTI + PREADJ + C + POSADJ)

# POS

if not CUANTI == CUANTIsus:
  if NUM == "SINGULAR":
    POSyes = random.choice(['mi ', 'tu ', 'su ', 'nuestr@ '])
  if NUM == "PLURAL":
    POSyes == random.choice(['mis ', 'tus ', 'sus ', 'nuestr@s '])
  POS = random.choice([POSyes, ''])
else:
  POS = ''

# print(POSyes)
# print(POS == POSyes)
# print(POS + CUANTI + PREADJ + C + POSADJ)

# ART

if not CUANTI == CUANTIsus and POS == '':
  if GEN == "MASCULINO" and NUM == "SINGULAR":
    ART = random.choice(['el ', 'un '])
  if GEN == "MASCULINO" and NUM == "PLURAL":
    ART = random.choice(['los ', 'unos '])
  if GEN == "FEMENINO" and NUM == "SINGULAR":
    ART = random.choice(['la ', 'una '])
  if GEN == "FEMENINO" and NUM == "PLURAL":
    ART = random.choice(['las ', 'unas '])

# print(not CUANTI == CUANTIsus)
# print(POS == '')
# print(ART + POS + CUANTI + PREADJ + C + POSADJ)

# REFIX

FN = ART + POS + CUANTI + PREADJ + C + POSADJ
if GEN == "MASCULINO":
  FN = FN.replace("@", "o")
  FN = FN.replace("$", "")
  FN = FN.replace("&", "e")
if GEN == "FEMENINO":
  FN = FN.replace("@", "a")
  FN = FN.replace("$", "a")
  FN = FN.replace("&", "a")
FN = FN.replace("/", "")

# NEXUS DE FN

FN1 = FN
COORD = FN1 + "y "
PREPO1 = FN1 + random.choice(["de ", "para ", "ante ", "con ", "sin ", "tras "])

# RESET

GEN = ''
NUM = ''
C = ''
ART = ''
CUANTI = ''
CUANTInosus = ''
CUANTIsus = ''
CUANTIyes = ''
POS = ''
POSADJ = ''
POSADJyes = ''
POSyes = ''
PREADJ = ''
PREADJyes = ''
PREFIX = ''
FN = ''

#

# GÉNERO Y NÚMERO

GEN = random.choice(["MASCULINO", "FEMENINO"])
NUM = random.choice(["SINGULAR", "PLURAL"])

# CABEZA

if GEN == "MASCULINO" and NUM == "SINGULAR":
  C = random.choice(['perro ', 'gato ', 'hombre ', 'presidente ', 'ministro ', 'enfermero ', 'capitán ', 'bibliotecario ', 'profesor ', 'programador ', 'hermano ', 'sacerdote ', 'alumno '])
if GEN == "MASCULINO" and NUM == "PLURAL":
  C = random.choice(['perros ', 'gatos ', 'hombres ', 'presidentes ', 'ministros ', 'enfermeros ', 'capitanes ', 'bibliotecarios ', 'profesores ', 'programadores ', 'hermanos ', 'sacerdotes ', 'alumnos '])
if GEN == "FEMENINO" and NUM == "SINGULAR":
  C = random.choice(['perra ', 'gata ', 'mujer ', 'presidenta ', 'ministra ', 'enfermera ', 'capitana ', 'bibliotecaria ', 'profesora ', 'programadora ', 'hermana ', 'sacerdotiza ', 'alumna '])
if GEN == "FEMENINO" and NUM == "PLURAL":
  C = random.choice(['perras ', 'gatas ', 'mujeres ', 'presidentas ', 'ministras ', 'enfermeras ', 'capitanas ', 'bibliotecarias ', 'profesoras ', 'programadoras ', 'hermanas ', 'sacerdotizas ', 'alumnas '])

# print(GEN)
# print(NUM)
# print(C)

# POSADJ

if NUM == "SINGULAR":
  POSADJyes = random.choice(['roj@ ', 'solter@ ', 'valiente ', 'soberbi@ ', 'peruan@ ', 'campestre ', 'frances$ ', 'actual ', 'antigu@ ', 'expert@ ', 'corrupt@ ', 'ladron$ '])
if NUM == "PLURAL":
  POSADJyes = random.choice(['roj@s ', 'solter@s ', 'valientes ', 'soberbi@s ', 'peruan@s ', 'campestres ', 'frances&s ', 'actuales ', 'antigu@s ', 'expert@s ', 'corrupt@s ', 'ladron&s '])
POSADJ = random.choice([POSADJyes, ''])

# print(POSADJyes)
# print(POSADJ == POSADJyes)
# print(C + POSADJ)

# PREADJ

if NUM == "SINGULAR":
  PREADJyes = random.choice(['terrible ', 'increíble ', 'gran ', 'grandios@ ', 'magnífic@ ', 'viej@ '])
if NUM == "PLURAL":
  PREADJyes = random.choice(['terribles ', 'increíbles ', 'grandes ', 'grandios@s ', 'magnífic@s ', 'viej@s '])
PREADJ = random.choice([PREADJyes, ''])

# print(PREADJyes)
# print(PREADJ == PREADJyes)
# print(PREADJ + C + POSADJ)

# CUANTI

if NUM == "SINGULAR":
  CUANTIsus = random.choice(['tod@ ', 'cualquier ', 'cada ', 'algun$ ', 'ningun$ '])
  CUANTInosus = ''
if NUM == "PLURAL":
  CUANTIsus = random.choice(['demasiad@s ', 'vari@s ', 'algun@s '])
  CUANTInosus = random.choice(['poc@s ','dos ','tres ','cuatro ','cinco '])
CUANTIyes = random.choice([CUANTIsus, CUANTInosus])
CUANTI = random.choice([CUANTIyes, ''])

# print(CUANTIyes)
# print(CUANTI != '')
# print(CUANTI + PREADJ + C + POSADJ)

# POS

if not CUANTI == CUANTIsus:
  if NUM == "SINGULAR":
    POSyes = random.choice(['mi ', 'tu ', 'su ', 'nuestr@ '])
  if NUM == "PLURAL":
    POSyes == random.choice(['mis ', 'tus ', 'sus ', 'nuestr@s '])
  POS = random.choice([POSyes, ''])
else:
  POS = ''

# print(POSyes)
# print(POS == POSyes)
# print(POS + CUANTI + PREADJ + C + POSADJ)

# ART

if not CUANTI == CUANTIsus and POS == '':
  if GEN == "MASCULINO" and NUM == "SINGULAR":
    ART = random.choice(['el ', 'un '])
  if GEN == "MASCULINO" and NUM == "PLURAL":
    ART = random.choice(['los ', 'unos '])
  if GEN == "FEMENINO" and NUM == "SINGULAR":
    ART = random.choice(['la ', 'una '])
  if GEN == "FEMENINO" and NUM == "PLURAL":
    ART = random.choice(['las ', 'unas '])

# print(not CUANTI == CUANTIsus)
# print(POS == '')
# print(ART + POS + CUANTI + PREADJ + C + POSADJ)

# REFIX

FN = ART + POS + CUANTI + PREADJ + C + POSADJ
if GEN == "MASCULINO":
  FN = FN.replace("@", "o")
  FN = FN.replace("$", "")
  FN = FN.replace("&", "e")
if GEN == "FEMENINO":
  FN = FN.replace("@", "a")
  FN = FN.replace("$", "a")
  FN = FN.replace("&", "a")
FN = FN.replace("/", "")

# MIX

COORD = COORD + FN
PREPO1 = PREPO1 + FN
FN = random.choice([COORD, PREPO1, FN, ''])

# PRINT

print(FN)

### CONSTRUCTOR DE FRASES NOMINALES ###
# TERMINADO. v3
import random

#random.choice([])

# RESET

GEN = ''
NUM = ''
C = ''
ART = ''
CUANTI = ''
CUANTInosus = ''
CUANTIsus = ''
CUANTIyes = ''
POS = ''
POSADJ = ''
POSADJyes = ''
POSyes = ''
PREADJ = ''
PREADJyes = ''
PREFIX = ''
FN = ''

# GÉNERO Y NÚMERO

GEN = random.choice(["MASCULINO", "FEMENINO"])
NUM = random.choice(["SINGULAR", "PLURAL"])

# CABEZA

if GEN == "MASCULINO" and NUM == "SINGULAR":
  C = random.choice(['perro ', 'gato ', 'hombre ', 'presidente ', 'ministro ', 'enfermero ', 'capitán ', 'bibliotecario ', 'profesor ', 'programador ', 'hermano ', 'sacerdote ', 'alumno '])
if GEN == "MASCULINO" and NUM == "PLURAL":
  C = random.choice(['perros ', 'gatos ', 'hombres ', 'presidentes ', 'ministros ', 'enfermeros ', 'capitanes ', 'bibliotecarios ', 'profesores ', 'programadores ', 'hermanos ', 'sacerdotes ', 'alumnos '])
if GEN == "FEMENINO" and NUM == "SINGULAR":
  C = random.choice(['perra ', 'gata ', 'mujer ', 'presidenta ', 'ministra ', 'enfermera ', 'capitana ', 'bibliotecaria ', 'profesora ', 'programadora ', 'hermana ', 'sacerdotiza ', 'alumna '])
if GEN == "FEMENINO" and NUM == "PLURAL":
  C = random.choice(['perras ', 'gatas ', 'mujeres ', 'presidentas ', 'ministras ', 'enfermeras ', 'capitanas ', 'bibliotecarias ', 'profesoras ', 'programadoras ', 'hermanas ', 'sacerdotizas ', 'alumnas '])

# print(GEN)
# print(NUM)
# print(C)

# POSADJ

if NUM == "SINGULAR":
  POSADJyes = random.choice(['roj@ ', 'solter@ ', 'valiente ', 'soberbi@ ', 'peruan@ ', 'campestre ', 'frances$ ', 'actual ', 'antigu@ ', 'expert@ ', 'corrupt@ ', 'ladron$ '])
if NUM == "PLURAL":
  POSADJyes = random.choice(['roj@s ', 'solter@s ', 'valientes ', 'soberbi@s ', 'peruan@s ', 'campestres ', 'frances&s ', 'actuales ', 'antigu@s ', 'expert@s ', 'corrupt@s ', 'ladron&s '])
POSADJ = random.choice([POSADJyes, ''])

# print(POSADJyes)
# print(POSADJ == POSADJyes)
# print(C + POSADJ)

# PREADJ

if NUM == "SINGULAR":
  PREADJyes = random.choice(['terrible ', 'increíble ', 'gran ', 'grandios@ ', 'magnífic@ ', 'viej@ '])
if NUM == "PLURAL":
  PREADJyes = random.choice(['terribles ', 'increíbles ', 'grandes ', 'grandios@s ', 'magnífic@s ', 'viej@s '])
PREADJ = random.choice([PREADJyes, ''])

# print(PREADJyes)
# print(PREADJ == PREADJyes)
# print(PREADJ + C + POSADJ)

# CUANTI

if NUM == "SINGULAR":
  CUANTIsus = random.choice(['tod@ ', 'cualquier ', 'cada ', 'algun$ ', 'ningun$ '])
  CUANTInosus = ''
if NUM == "PLURAL":
  CUANTIsus = random.choice(['demasiad@s ', 'vari@s ', 'algun@s '])
  CUANTInosus = random.choice(['poc@s ','dos ','tres ','cuatro ','cinco '])
CUANTIyes = random.choice([CUANTIsus, CUANTInosus])
CUANTI = random.choice([CUANTIyes, ''])

# print(CUANTIyes)
# print(CUANTI != '')
# print(CUANTI + PREADJ + C + POSADJ)

# POS

if not CUANTI == CUANTIsus:
  if NUM == "SINGULAR":
    POSyes = random.choice(['mi ', 'tu ', 'su ', 'nuestr@ '])
  if NUM == "PLURAL":
    POSyes == random.choice(['mis ', 'tus ', 'sus ', 'nuestr@s '])
  POS = random.choice([POSyes, ''])
else:
  POS = ''

# print(POSyes)
# print(POS == POSyes)
# print(POS + CUANTI + PREADJ + C + POSADJ)

# ART

if not CUANTI == CUANTIsus and POS == '':
  if GEN == "MASCULINO" and NUM == "SINGULAR":
    ART = random.choice(['el ', 'un '])
  if GEN == "MASCULINO" and NUM == "PLURAL":
    ART = random.choice(['los ', 'unos '])
  if GEN == "FEMENINO" and NUM == "SINGULAR":
    ART = random.choice(['la ', 'una '])
  if GEN == "FEMENINO" and NUM == "PLURAL":
    ART = random.choice(['las ', 'unas '])

# print(not CUANTI == CUANTIsus)
# print(POS == '')
# print(ART + POS + CUANTI + PREADJ + C + POSADJ)

# REFIX

FN = ART + POS + CUANTI + PREADJ + C + POSADJ
if GEN == "MASCULINO":
  FN = FN.replace("@", "o")
  FN = FN.replace("$", "")
  FN = FN.replace("&", "e")
if GEN == "FEMENINO":
  FN = FN.replace("@", "a")
  FN = FN.replace("$", "a")
  FN = FN.replace("&", "a")
FN = FN.replace("/", "")

# NEXUS DE FN

FN1 = FN
COORD = FN1 + "y "
PREPO1 = FN1 + random.choice(["de ", "para ", "ante ", "con ", "sin ", "tras "])

# RESET

GEN = ''
NUM = ''
C = ''
ART = ''
CUANTI = ''
CUANTInosus = ''
CUANTIsus = ''
CUANTIyes = ''
POS = ''
POSADJ = ''
POSADJyes = ''
POSyes = ''
PREADJ = ''
PREADJyes = ''
PREFIX = ''
FN = ''

#

# GÉNERO Y NÚMERO

GEN = random.choice(["MASCULINO", "FEMENINO"])
NUM = random.choice(["SINGULAR", "PLURAL"])

# CABEZA

if GEN == "MASCULINO" and NUM == "SINGULAR":
  C = random.choice(['perro ', 'gato ', 'hombre ', 'presidente ', 'ministro ', 'enfermero ', 'capitán ', 'bibliotecario ', 'profesor ', 'programador ', 'hermano ', 'sacerdote ', 'alumno '])
if GEN == "MASCULINO" and NUM == "PLURAL":
  C = random.choice(['perros ', 'gatos ', 'hombres ', 'presidentes ', 'ministros ', 'enfermeros ', 'capitanes ', 'bibliotecarios ', 'profesores ', 'programadores ', 'hermanos ', 'sacerdotes ', 'alumnos '])
if GEN == "FEMENINO" and NUM == "SINGULAR":
  C = random.choice(['perra ', 'gata ', 'mujer ', 'presidenta ', 'ministra ', 'enfermera ', 'capitana ', 'bibliotecaria ', 'profesora ', 'programadora ', 'hermana ', 'sacerdotiza ', 'alumna '])
if GEN == "FEMENINO" and NUM == "PLURAL":
  C = random.choice(['perras ', 'gatas ', 'mujeres ', 'presidentas ', 'ministras ', 'enfermeras ', 'capitanas ', 'bibliotecarias ', 'profesoras ', 'programadoras ', 'hermanas ', 'sacerdotizas ', 'alumnas '])

# print(GEN)
# print(NUM)
# print(C)

# POSADJ

if NUM == "SINGULAR":
  POSADJyes = random.choice(['roj@ ', 'solter@ ', 'valiente ', 'soberbi@ ', 'peruan@ ', 'campestre ', 'frances$ ', 'actual ', 'antigu@ ', 'expert@ ', 'corrupt@ ', 'ladron$ '])
if NUM == "PLURAL":
  POSADJyes = random.choice(['roj@s ', 'solter@s ', 'valientes ', 'soberbi@s ', 'peruan@s ', 'campestres ', 'frances&s ', 'actuales ', 'antigu@s ', 'expert@s ', 'corrupt@s ', 'ladron&s '])
POSADJ = random.choice([POSADJyes, ''])

# print(POSADJyes)
# print(POSADJ == POSADJyes)
# print(C + POSADJ)

# PREADJ

if NUM == "SINGULAR":
  PREADJyes = random.choice(['terrible ', 'increíble ', 'gran ', 'grandios@ ', 'magnífic@ ', 'viej@ '])
if NUM == "PLURAL":
  PREADJyes = random.choice(['terribles ', 'increíbles ', 'grandes ', 'grandios@s ', 'magnífic@s ', 'viej@s '])
PREADJ = random.choice([PREADJyes, ''])

# print(PREADJyes)
# print(PREADJ == PREADJyes)
# print(PREADJ + C + POSADJ)

# CUANTI

if NUM == "SINGULAR":
  CUANTIsus = random.choice(['tod@ ', 'cualquier ', 'cada ', 'algun$ ', 'ningun$ '])
  CUANTInosus = ''
if NUM == "PLURAL":
  CUANTIsus = random.choice(['demasiad@s ', 'vari@s ', 'algun@s '])
  CUANTInosus = random.choice(['poc@s ','dos ','tres ','cuatro ','cinco '])
CUANTIyes = random.choice([CUANTIsus, CUANTInosus])
CUANTI = random.choice([CUANTIyes, ''])

# print(CUANTIyes)
# print(CUANTI != '')
# print(CUANTI + PREADJ + C + POSADJ)

# POS

if not CUANTI == CUANTIsus:
  if NUM == "SINGULAR":
    POSyes = random.choice(['mi ', 'tu ', 'su ', 'nuestr@ '])
  if NUM == "PLURAL":
    POSyes == random.choice(['mis ', 'tus ', 'sus ', 'nuestr@s '])
  POS = random.choice([POSyes, ''])
else:
  POS = ''

# print(POSyes)
# print(POS == POSyes)
# print(POS + CUANTI + PREADJ + C + POSADJ)

# ART

if not CUANTI == CUANTIsus and POS == '':
  if GEN == "MASCULINO" and NUM == "SINGULAR":
    ART = random.choice(['el ', 'un '])
  if GEN == "MASCULINO" and NUM == "PLURAL":
    ART = random.choice(['los ', 'unos '])
  if GEN == "FEMENINO" and NUM == "SINGULAR":
    ART = random.choice(['la ', 'una '])
  if GEN == "FEMENINO" and NUM == "PLURAL":
    ART = random.choice(['las ', 'unas '])

# print(not CUANTI == CUANTIsus)
# print(POS == '')
# print(ART + POS + CUANTI + PREADJ + C + POSADJ)

# REFIX

FN = ART + POS + CUANTI + PREADJ + C + POSADJ
if GEN == "MASCULINO":
  FN = FN.replace("@", "o")
  FN = FN.replace("$", "")
  FN = FN.replace("&", "e")
if GEN == "FEMENINO":
  FN = FN.replace("@", "a")
  FN = FN.replace("$", "a")
  FN = FN.replace("&", "a")
FN = FN.replace("/", "")

# MIX

COORD = COORD + FN
PREPO1 = PREPO1 + FN
FN = random.choice([COORD, PREPO1, FN, ''])

# PRINT

print(FN)

miau = input("Coloca aquí el tipo de miau que quieres que diga el gato: ")
gato = input("Coloca aquí cómo quieres que se llame el gato: ")
cuantas = int(input("Coloca aquí cuántas veces quieres que el gato diga miau: "))
texto = "[" + gato + "]   : " + ((miau + " ") * cuantas)
print(texto)

import random

max_t = int(input("Ingrese aquí el número máximo de turnos de juego (t): "))
memoria_1 = []
memoria_2 = []
memoria_3 = []
memoria_4 = []
memoria_5 = []
memoria_total = [memoria_1, memoria_2, memoria_3, memoria_4, memoria_5]
bancogeneral = ['hola', 'qué', 'tal', 'perro', 'gato']

for i in range(max_t):

  if i == 0:
    print("[" + str(i) + "] :" + str(memoria_total))

  memorias = random.sample(memoria_total, 5)

  if len(memorias[0]) == 0:
    memorias[0].append(random.choice(bancogeneral))
  if len(memorias[0]) > 0:
    expresion = random.choice(memorias[0])
    if expresion in memorias[1]:
      memoria_total.remove(memorias[1])
      memoria_total.remove(memorias[0])
      memorias[0] = [expresion]
      memorias[1] = [expresion]
      memoria_total.append(memorias[0])
      memoria_total.append(memorias[1])
    else:
      memorias[1].append(expresion)

  print("[" + str(i + 1) + "] :" + str(memoria_total))

import random

random.seed(1)
max_t = int(input("Ingrese aquí el número máximo de turnos de juego (t): "))
jugadores = int(input("Ingrese aquí el número de jugadores: "))
memoria_1 = []
memoria_2 = []
memoria_3 = []
memoria_4 = []
memoria_5 = []
memoria_total = [memoria_1, memoria_2, memoria_3, memoria_4, memoria_5]
bancogeneral = ['hola', 'qué', 'tal', 'perro', 'gato']

for i in range(max_t):

  if i == 0:
    print("[" + str(i) + "] :" + str(memoria_total), end = "\n\n")

  memorias = random.sample(list(range(len(memoria_total))), 2)
  print("> Juegan jugadores " + str(memorias[0] + 1) + " (hablante) y " + str(memorias[1] + 1) + " (oyente).", end = "\n\n")

  if len(memoria_total[memorias[0]]) == 0:
    memoria_total[memorias[0]].append(random.choice(bancogeneral))
  if len(memoria_total[memorias[0]]) > 0:
    expresion = random.choice(memoria_total[memorias[0]])
    if expresion in memoria_total[memorias[1]]:
      memoria_total[memorias[0]] = [expresion]
      memoria_total[memorias[1]] = [expresion]
    else:
      memoria_total[memorias[1]].append(expresion)

  print("[" + str(i + 1) + "] : " + str(memoria_total), end = "\n\n")

print("<<<<-------------------------->>>>\n          THE NAMING GAME         \n<<<<-------------------------->>>>\n")

import random
import matplotlib.pyplot as plt
import numpy as np

jugadores = int(input("Ingrese aquí el número de jugadores: "))
memoria_total = {}
for i in range(1, jugadores + 1):
  memoria_total[i] = []

bancogeneral = list(set(input("Ingrese aquí un texto grandísimo de muchas palabras: ").split()))
# Copie el siguiente texto de ejemplo, si desea: Lorem ipsum dolor sit amet consectetur adipiscing elit bibendum, elementum habitasse facilisis vehicula hendrerit nisi tellus non, rhoncus feugiat pharetra erat auctor nam duis. Dis neque eu tempus eleifend hendrerit consequat nisl, vivamus viverra augue integer sociosqu parturient gravida, hac venenatis felis sagittis faucibus ridiculus. Mus maecenas parturient dignissim penatibus bibendum condimentum facilisis, et ut torquent nisl suspendisse turpis dis neque, venenatis enim litora sociis habitant taciti. Duis turpis torquent ullamcorper placerat tristique platea sociis eros scelerisque, justo cursus cras ultricies fames congue malesuada blandit. Pharetra at rutrum leo congue id pretium cum, fermentum conubia platea mollis class gravida condimentum curae, faucibus quam vitae nostra litora natoque. Molestie convallis sociis nostra justo lacus lobortis, magnis euismod faucibus vestibulum conubia, enim vel dui ad leo.

# max_t = int(input("Ingrese aquí el número máximo de turnos de juego (t): "))
# for i in range(max_t):
for i in range(100000000000000000000000):

  counter1 = []
  counter2 = []

  if i == 0:
    print("\n\n[" + str(i) + "] :   " + str(memoria_total), end = "\n\n")

  memorias = random.sample(list(memoria_total.keys()), 2)

  if len(memoria_total[memorias[0]]) == 0:
    memoria_total[memorias[0]].append(random.choice(bancogeneral))
  if len(memoria_total[memorias[0]]) > 0:
    expresion = random.choice(memoria_total[memorias[0]])
    if expresion in memoria_total[memorias[1]]:
      memoria_total[memorias[0]] = [expresion]
      memoria_total[memorias[1]] = [expresion]
    else:
      memoria_total[memorias[1]].append(expresion)

  for j in range(len(memoria_total)):
    for k in range(len(memoria_total[j + 1])):
      counter1.append(memoria_total[j + 1][k])
      if memoria_total[j + 1][k] not in counter2:
        counter2.append(memoria_total[j + 1][k])

  ###

  print("     " + str(memorias[0]) + " -> " + str(memorias[1]) + ":  " + expresion, end = "\n\n")

  print("[" + str(i + 1) + "] :   " + str(memoria_total), end = "\n\n")

  if all(valor == list(memoria_total.values())[0] for valor in list(memoria_total.values())):
    break



print("\nVICTORIA: en el turno " + str(i + 1) + " con la palabra " + str(list(memoria_total.values())[0]))

import random

random.seed(42)
a = random.randint(1, 10)
print(a)